.TH CKSFV 1
.\" NAME should be all caps, SECTION should be 1-8, maybe w/ subsection
.\" other parms are allowed: see man(7), man(1)
.SH NAME
cksfv \- tests and creates simple file verification (SFV) listings
.SH SYNOPSIS
.B cksfv
.I "[-biq] [-C directory] [-f file.sfv] [file ...]"
.br
.SH "DESCRIPTION"
Some files that you download will come with a .sfv file.
.BR cksfv
is used to
verify that the files that you received are the same as the originals.
cksfv is a program that can use the .sfv file to verify the downloaded
files.  Also, it can be used to create new .sfv files.
.PP
.BR md5sum
(1) or
.BR sha1sum
(1)
are the suggested ways of checksuming new files. cksfv should only
be used for compatibility with other systems.

.SH OPTIONS
These options are available
.TP
.B \-b
strip dirnames from filenames that are checksumed. loads the files from
original positions, but prints only basenames to catalogue in sfv file.
.TP
.B \-C
change to directory for processing
.B \-f
 .sfv file to verify
.TP
.B \-i
ignore case on filenames
.TP
.B \-q
quiet, only prints error messages
.TP
.B \-v
verbose, by default this option is on

.SH EXAMPLES
.nf
Check checksums of files listed in 'files.sfv':
.ft B
cksfv -f files.sfv

.ft R
Create checksums for a bunch of files:
.ft B
cksfv *.gz > files.sfv

.ft R
Check checksum of case-insensitive filenames listed in 'files.sfv'.
This is sometimes useful with files created by operating systems
that have case-insensitive filesystem names.
.ft B
cksfv -i -f files.sfv

.ft R
Check checksums of files 'foo' and 'bar' listed in 'files.sfv':
.ft B
cksfv -f files.sfv foo bar

.ft R
Create checksums of files matching /foo/bar/* and strip dirnames away:
.ft B
cksfv -b /foo/bar/* > files.sfv

.SH "SEE ALSO"
.BR basename (1)
.BR dirname (1)
.BR md5sum (1)
.BR sha1sum (1)

.SH AUTHOR
This manual page was written by Stefan Alfredsson <stefan@alfredsson.org>,
for the Debian GNU/Linux system (but may be used by others). It was later
modified by Heikki Orsila <heikki.orsila@iki.fi>.
